name: rokomari_toast
description: "a new Rokomari toast which is the wrapper of the SnackBar"
version: 0.0.1
homepage: https://github.com/iftakher36/Rokomari-Toast.git

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1



flutter:
  assets:
    - assets/
